<?php

return array(
"Abejorral-Antioquia",
"Abriaqui-Antioquia",
"Alejandria-Antioquia",
"Amaga-Antioquia",
"Amalfi-Antioquia",
"Andes-Antioquia",
"Angelopolis-Antioquia",
"Angostura-Antioquia",
"Anori-Antioquia",
"Anza-Antioquia",
"Arboletes-Antioquia",
"Argelia-Antioquia",
"Armenia-Antioquia",
"Belmira-Antioquia",
"Betania-Antioquia",
"Betulia-Antioquia",
"Briceño-Antioquia",
"Buritica-Antioquia",
"Caceres-Antioquia",
"Caicedo-Antioquia",
"Campamento-Antioquia",
"Cañasgordas-Antioquia",
"Caracoli-Antioquia",
"Caramanta-Antioquia",
"Carepa-Antioquia",
"Carolina-Antioquia",
"Chigorodo-Antioquia",
"Cisneros-Antioquia",
"Ciudad Bolivar-Antioquia",
"Cocorna-Antioquia",
"Concepcion-Antioquia",
"Concordia-Antioquia",
"Currulao-Antioquia",
"Don Matias-Antioquia",
"Ebejico-Antioquia",
"El Bagre-Antioquia",
"El Carmen De Viboral-Antioquia",
"El Santuario-Antioquia",
"El Valle-Antioquia",
"Entrerrios-Antioquia",
"Fredonia-Antioquia",
"Frontino-Antioquia",
"Giraldo-Antioquia",
"Gomez Plata-Antioquia",
"Granada-Antioquia",
"Guadalupe-Antioquia",
"Guatape-Antioquia",
"Heliconia-Antioquia",
"Hispania-Antioquia",
"Ituango-Antioquia",
"Jardin-Antioquia",
"Jerico-Antioquia",
"La Pintada-Antioquia",
"La Union-Antioquia",
"Liborina-Antioquia",
"Maceo-Antioquia",
"Montebello-Antioquia",
"Murindo-Antioquia",
"Mutata-Antioquia",
"Nariño-Antioquia",
"Nechi-Antioquia",
"Necocli-Antioquia",
"Nueva Colonia-Antioquia",
"Olaya-Antioquia",
"Palermo-Antioquia",
"Peñol-Antioquia",
"Peque-Antioquia",
"Pueblorrico-Antioquia",
"Puerto Claver-Antioquia",
"Puerto Nare-Antioquia",
"Puerto Perales Nuevo-Antioquia",
"Remedios-Antioquia",
"Sabanalarga-Antioquia",
"Salgar-Antioquia",
"San Andres De Cuerquia-Antioquia",
"San Carlos-Antioquia",
"San Cristobal-Antioquia",
"San Francisco-Antioquia",
"San Jose De La Montaña-Antioquia",
"San Luis-Antioquia",
"San Pedro De Uraba-Antioquia",
"San Rafael-Antioquia",
"San Roque-Antioquia",
"San Vicente-Antioquia",
"Santa Barbara-Antioquia",
"Santa Rosa De Osos-Antioquia",
"Santafe De Antioquia-Antioquia",
"Santo Domingo-Antioquia",
"Segovia-Antioquia",
"Sonson-Antioquia",
"Sopetran-Antioquia",
"Tamesis-Antioquia",
"Taraza-Antioquia",
"Tarso-Antioquia",
"Titiribi-Antioquia",
"Toledo-Antioquia",
"Turbo-Antioquia",
"Uramita-Antioquia",
"Urrao-Antioquia",
"Valdivia-Antioquia",
"Valparaiso-Antioquia",
"Vegachi-Antioquia",
"Venecia-Antioquia",
"Vigia Del Fuerte-Antioquia",
"Yali-Antioquia",
"Yarumal-Antioquia",
"Yolombo-Antioquia",
"Arauquita-Arauca",
"Cravo Norte-Arauca",
"Puerto Rondon-Arauca",
"Saravena-Arauca",
"Aguada De Pablo-Atlantico",
"Campeche-Atlantico",
"Campo De La Cruz-Atlantico",
"Candelaria-Atlantico",
"Caracoli-Atlantico",
"Cascajal-Atlantico",
"Juan Mina-Atlantico",
"La Peña-Atlantico",
"Luruaco-Atlantico",
"Manati-Atlantico",
"Palmar De Varela-Atlantico",
"Piojo-Atlantico",
"Polonuevo-Atlantico",
"Ponedera-Atlantico",
"Puerto Giraldo-Atlantico",
"Repelon-Atlantico",
"Santa Cruz-Atlantico",
"Santa Lucia-Atlantico",
"Suan-Atlantico",
"Tubara-Atlantico",
"Achi-Bolivar",
"Altos Del Rosario-Bolivar",
"Arenal-Bolivar",
"Arroyohondo-Bolivar",
"Barranco De Loba-Bolivar",
"Calamar-Bolivar",
"Cicuco-Bolivar",
"Clemencia B-Bolivar",
"Cordoba-Bolivar",
"El Guamo-Bolivar",
"El Peñon-Bolivar",
"Gambote-Bolivar",
"Hatillo De Loba-Bolivar",
"Juan Arias-Bolivar",
"Mahates-Bolivar",
"Margarita-Bolivar",
"Montecristo-Bolivar",
"Norosi-Bolivar",
"Pinillos-Bolivar",
"Pontezuela-Bolivar",
"Punta De Cartagena-Bolivar",
"Regidor-Bolivar",
"Rio Viejo-Bolivar",
"San Cristobal-Bolivar",
"San Estanislao-Bolivar",
"San Fernando-Bolivar",
"San Jacinto Del Cauca-Bolivar",
"San Martin-Bolivar",
"San Pablo-Bolivar",
"Santa Ana-Bolivar",
"Santa Catalina-Bolivar",
"Santa Rosa De Lima-Bolivar",
"Sincerin-Bolivar",
"Soplaviento-Bolivar",
"Talaigua Nuevo-Bolivar",
"Tiquisio Nuevo-Bolivar",
"Turbana-Bolivar",
"Villanueva-Bolivar",
"Yati-Bolivar",
"Almeida-Boyaca",
"Belencito-Boyaca",
"Beteitiva-Boyaca",
"Boyaca-Boyaca",
"Briceño-Boyaca",
"Busbanza-Boyaca",
"Caldas-Boyaca",
"Campohermoso-Boyaca",
"Cerinza-Boyaca",
"Chiquiza-Boyaca",
"Chitaraque-Boyaca",
"Coper-Boyaca",
"Corrales-Boyaca",
"Covarachia-Boyaca",
"Cubara-Boyaca",
"Cuitiva-Boyaca",
"Floresta-Boyaca",
"Gachantiva-Boyaca",
"Gameza-Boyaca",
"Guacamayas-Boyaca",
"Iza-Boyaca",
"La Capilla-Boyaca",
"La Uvita-Boyaca",
"La Victoria-Boyaca",
"Labranzagrande-Boyaca",
"Macanal-Boyaca",
"Motavita-Boyaca",
"Paya-Boyaca",
"Pisba-Boyaca",
"Quipama-Boyaca",
"Rondon-Boyaca",
"San Eduardo-Boyaca",
"San Pablo De Borbur-Boyaca",
"Sativanorte-Boyaca",
"Sativasur-Boyaca",
"Sora-Boyaca",
"Susacon-Boyaca",
"Sutatenza-Boyaca",
"Togüi-Boyaca",
"Tota-Boyaca",
"Trinidad-Boyaca",
"Tunungua-Boyaca",
"Tutaza-Boyaca",
"Viracacha-Boyaca",
"Alto Tablazo-Caldas",
"Arauca-Caldas",
"Bajo Tablazo-Caldas",
"Guarinocito-Caldas",
"La Linda-Caldas",
"Marmato-Caldas",
"Marulanda-Caldas",
"Samana-Caldas",
"Samaria-Caldas",
"San Jose-Caldas",
"Victoria-Caldas",
"Albania-Caqueta",
"Campo Hermoso-Caqueta",
"Milan-Caqueta",
"Morelia-Caqueta",
"Solano-Caqueta",
"Solita-Caqueta",
"Valparaiso-Caqueta",
"Chameza-Casanare",
"La Salina-Casanare",
"Pore-Casanare",
"Recetor-Casanare",
"Sabanalarga-Casanare",
"Sacama-Casanare",
"San Luis De Palenque-Casanare",
"Almaguer-Cauca",
"Argelia-Cauca",
"Balboa-Cauca",
"Buenos Aires-Cauca",
"Caldono-Cauca",
"Coconuco-Cauca",
"El Bordo-Cauca",
"El Estrecho-Cauca",
"El Plateado-Cauca",
"El Tambo-Cauca",
"Guachene-Cauca",
"Guapi-Cauca",
"Inza-Cauca",
"Jambalo-Cauca",
"La Sierra-Cauca",
"La Vega-Cauca",
"Mercaderes-Cauca",
"Micay-Cauca",
"Miranda-Cauca",
"Morales-Cauca",
"Ortigal-Cauca",
"Padilla-Cauca",
"Paispamba-Cauca",
"Patia-Cauca",
"Piamonte-Cauca",
"Purace-Cauca",
"Rosas-Cauca",
"San Sebastian-Cauca",
"Santa Rosa-Cauca",
"Santiago-Cauca",
"Silvia-Cauca",
"Suarez-Cauca",
"Sucre-Cauca",
"Timbiqui-Cauca",
"Toribio-Cauca",
"Totoro-Cauca",
"Tunia-Cauca",
"Astrea-Cesar",
"Casacaza-Cesar",
"Gonzalez-Cesar",
"Tamalameque-Cesar",
"Acandi-Choco",
"Andagoya-Choco",
"Animas-Choco",
"Bagado-Choco",
"Bahia Solano Mutis-Choco",
"Belen De Bajira-Choco",
"Bellavista-Choco",
"Bete-Choco",
"Certegui-Choco",
"Condoto-Choco",
"Curbarado-Choco",
"El Carmen De Atrato-Choco",
"Istmina-Choco",
"Jurado-Choco",
"Lloro-Choco",
"Managru-Choco",
"Novita-Choco",
"Nuqui-Choco",
"Paimado-Choco",
"Pie De Pato-Choco",
"Pizarro-Choco",
"Puerto Meluk-Choco",
"Riosucio-Choco",
"San Jose Del Palmar-Choco",
"Santa Genoveva De Docordo-Choco",
"Santa Rita-Choco",
"Sipi-Choco",
"Tado-Choco",
"Unguia-Choco",
"Yuto-Choco",
"Canalete-Cordoba",
"Cerromatoso-Cordoba",
"Cordoba-Cordoba",
"Los Garzones-Cordoba",
"Planeta Rica-Cordoba",
"Puerto Libertador-Cordoba",
"San Carlos-Cordoba",
"San Jose De Ure-Cordoba",
"Beltran-Cundinamarca",
"Bituima-Cundinamarca",
"Carmen De Carupa-Cundinamarca",
"Chaguani-Cundinamarca",
"Choconta-Cundinamarca",
"Cogua-Cundinamarca",
"El Peñon-Cundinamarca",
"Fuquene-Cundinamarca",
"Gachala-Cundinamarca",
"Gachancipa-Cundinamarca",
"Gacheta-Cundinamarca",
"Granada-Cundinamarca",
"Guacheta-Cundinamarca",
"Guataqui-Cundinamarca",
"Guatavita-Cundinamarca",
"Gutierrez-Cundinamarca",
"Jerusalen-Cundinamarca",
"Junin-Cundinamarca",
"La Gran Vía-Cundinamarca",
"La Palma-Cundinamarca",
"La Peña-Cundinamarca",
"La Vega-Cundinamarca",
"La Victoria-Cundinamarca",
"Lenguazaque-Cundinamarca",
"Limoncitos-Cundinamarca",
"Nariño-Cundinamarca",
"Nimaima-Cundinamarca",
"Nocaima-Cundinamarca",
"Pacho-Cundinamarca",
"Paime-Cundinamarca",
"Pasca-Cundinamarca",
"Pueblo Nuevo-Cundinamarca",
"Puerto Bogota-Cundinamarca",
"Puli-Cundinamarca",
"Ricaurte-Cundinamarca",
"San Antonio Del Tequendama-Cundinamarca",
"San Cayetano-Cundinamarca",
"San Francisco-Cundinamarca",
"Sesquile-Cundinamarca",
"Suesca-Cundinamarca",
"Supata-Cundinamarca",
"Susa-Cundinamarca",
"Tibacuy-Cundinamarca",
"Tibirita-Cundinamarca",
"Tibito-Cundinamarca",
"Tobia-Cundinamarca",
"Topaipi-Cundinamarca",
"Ubaque-Cundinamarca",
"Vergara-Cundinamarca",
"Villagomez-Cundinamarca",
"Zipacon-Cundinamarca",
"Calamar-Guaviare",
"El Retorno-Guaviare",
"Miraflores-Guaviare",
"Agrado-Huila",
"Belen-Huila",
"Bruselas-Huila",
"Caguan-Huila",
"Guayabal-Huila",
"La Argentina-Huila",
"Nataga-Huila",
"Pacarni-Huila",
"Palestina-Huila",
"Ulloa-Huila",
"Dibulla-La Guajira",
"La Jagua Del Pilar-La Guajira",
"La Paz-La Guajira",
"Manaure-La Guajira",
"Mingueo-La Guajira",
"San Juan Del Cesar-La Guajira",
"Algarrobo-Magdalena",
"Buritaca-Magdalena",
"Carreto-Magdalena",
"Cerro San Antonio-Magdalena",
"Concordia-Magdalena",
"El Piðon-Magdalena",
"El Reten-Magdalena",
"Guacamayal-Magdalena",
"Guachaca-Magdalena",
"Guamal-Magdalena",
"Palermo-Magdalena",
"Prado - Sevilla-Magdalena",
"Puebloviejo-Magdalena",
"Punta De Piedras-Magdalena",
"Remolino-Magdalena",
"Sabanas-Magdalena",
"Salamina-Magdalena",
"San Angel-Magdalena",
"Santa Barbara De Pinto-Magdalena",
"Santa Rosalia-Magdalena",
"Sitionuevo-Magdalena",
"Tenerife-Magdalena",
"El Calvario-Meta",
"La Macarena-Meta",
"San Juan Del Losada-Meta",
"San Juanito-Meta",
"Uribe-Meta",
"Alban-Nariño",
"Aldana-Nariño",
"Ancuya-Nariño",
"Barbacoas-Nariño",
"Belen-Nariño",
"Berruecos-Nariño",
"Bocas De Satinga-Nariño",
"Carlosama-Nariño",
"Catambuco-Nariño",
"Chachagüi-Nariño",
"Consaca-Nariño",
"Contadero-Nariño",
"Cordoba N-Nariño",
"Cumbal-Nariño",
"Cumbitara-Nariño",
"El Charco-Nariño",
"El Encano-Nariño",
"El Peñol-Nariño",
"El Rosario-Nariño",
"El Tablón De Gomez-Nariño",
"Funes-Nariño",
"Guachaves-Nariño",
"Guachucal-Nariño",
"Gualmatán-Nariño",
"Iles-Nariño",
"Iscuande-Nariño",
"La Florida-Nariño",
"La Tola-Nariño",
"Leiva-Nariño",
"Linares-Nariño",
"Mosquera-Nariño",
"Nariño-Nariño",
"Olaya Herrera-Nariño",
"Ospina-Nariño",
"Payan-Nariño",
"Piedrancha-Nariño",
"Policarpa-Nariño",
"Potosi-Nariño",
"Providencia-Nariño",
"Pupiales-Nariño",
"Ricaurte-Nariño",
"Ricaurte-Nariño",
"Salahonda-Nariño",
"San Bernardo-Nariño",
"San Jose-Nariño",
"San Jose-Nariño",
"San Lorenzo-Nariño",
"San Pedro De Cartago-Nariño",
"Santa Barbara-Nariño",
"Sapuyes-Nariño",
"Sotomayor-Nariño",
"Tangua-Nariño",
"Tumaco-Nariño",
"Yacuanquer-Nariño",
"Bochalema-Norte De Santander",
"Bucarasica-Norte De Santander",
"Cacota-Norte De Santander",
"Cucutilla-Norte De Santander",
"El Carmen-Norte De Santander",
"El Tarra-Norte De Santander",
"Gramalote-Norte De Santander",
"Hacari-Norte De Santander",
"Herran-Norte De Santander",
"La Floresta-Norte De Santander",
"La Jarra-Norte De Santander",
"La Playa-Norte De Santander",
"Labateca-Norte De Santander",
"Lourdes-Norte De Santander",
"Mutiscua-Norte De Santander",
"Pamplonita-Norte De Santander",
"Ragonvalia-Norte De Santander",
"San Bernardo De Bata-Norte De Santander",
"San Cayetano-Norte De Santander",
"Santiago-Norte De Santander",
"Teorama-Norte De Santander",
"Villa Caro-Norte De Santander",
"Colon-Putumayo",
"Puerto Guzman-Putumayo",
"Barcelona-Quindio",
"Cordoba-Quindio",
"Pijao-Quindio",
"Salento-Quindio",
"El Crucero De Combia-Risaralda",
"Pueblo Rico-Risaralda",
"Aguada-Santander",
"Betulia-Santander",
"Cabrera-Santander",
"Capitanejo-Santander",
"Cepita-Santander",
"Cerrito-Santander",
"Charta-Santander",
"Chima-Santander",
"El Llanito-Santander",
"Florian-Santander",
"Guapota-Santander",
"Guavata-Santander",
"Hato-Santander",
"Jesus Maria-Santander",
"Jordan Sube-Santander",
"Macaravita-Santander",
"Palmar-Santander",
"Palo Gordo-Santander",
"Puente Sogamoso-Santander",
"San Benito-Santander",
"San Benito Nuevo-Santander",
"San Joaquin-Santander",
"San Jose De Miranda-Santander",
"San Miguel-Santander",
"Santa Barbara-Santander",
"Simacota-Santander",
"Sogamoso-Santander",
"Sucre-Santander",
"Vado Real-Santander",
"Buenavista-Sucre",
"Caimito-Sucre",
"Chalan-Sucre",
"El Roble-Sucre",
"Guaranda-Sucre",
"Guayabal-Sucre",
"La Union-Sucre",
"Los Palmitos-Sucre",
"Majagual-Sucre",
"Morroa-Sucre",
"Ricaurte-Sucre",
"San Benito Abad-Sucre",
"San Juan De Betulia-Sucre",
"Tolu Viejo-Sucre",
"Alpujarra-Tolima",
"Falan-Tolima",
"Fresno-Tolima",
"Gualanday-Tolima",
"Herrera-Tolima",
"Pajonales-Tolima",
"Palocabildo-Tolima",
"Planadas-Tolima",
"Roncesvalles-Tolima",
"Santa Isabel-Tolima",
"Santiago Perez-Tolima",
"Tolemaida-Melgar-Tolima",
"Villahermosa-Tolima",
"Alcala-Valle",
"Amaime-Valle",
"Cascajal I-Valle",
"Dagua-Valle",
"El Cabuyal-Valle",
"El Carmelo-Valle",
"El Saladito-Valle",
"Guabitas-Valle",
"La Cumbre-Valle",
"Riofrio-Valle",
"San Antonio De Los Caballeros-Valle",
"Santa Elena-Valle",
"Ulloa-Valle",
"Vijes-Valle",
"Zaragoza-Valle",
"Caruru-Vaupes",
"Taraira-Vaupes",
"Cumaribo-Vichada",
"La Primavera-Vichada",
"Santa Rosalia-Vichada"
);